### ISSUE TITLE
Cannot swap shop pages.

### ISSUE THREAD

**Issue by Nubebuster** [7sat/DynamicShop#15]
I want to switch a shop page but that's not a feature. Also the way the config is managed it's hardly possible to do it manually.

Thanks in advance

**Comment by KevinDaGame** [comment]
What do you mean exactly? Do you mean it like being able to switch from shop page to another shop page?

**Comment by Nubebuster** [comment]
The option to change the order of the shop pages.

Example:
I have three pages. page 1, 2 and 3
I want to be able to change the order to 2, 1, 3

**Comment by KevinDaGame** [comment]
I believe in the config you can set startpage to be the default to pop up when doing /shop. On there you can create custom buttons leading to your shops, but also to run any other command. You can move these with your middle mouse button

**Comment by Nubebuster** [comment]
I am talking about when you're inside a shop.

**Comment by 7sat** [comment]
Premium version includes this feature
