### ISSUE TITLE
Lag spikes

### ISSUE THREAD

**Issue by Lambsus** [7sat/DynamicShop#33]
Hi, I'm getting lag spikes from this plugin: https://spark.lucko.me/#pU0sSpVpYk. I believe it is when the user flat file gets large.

**Comment by jmanpenilla** [comment]
Would you be willing to test out the changes in the draft PR I just made? [Here](https://anonymousfiles.io/gELuoRsJ/) is a jar

**Comment by jmanpenilla** [comment]
@7sat this should be closed unless it can be reproduced in 2.11.8

**Comment by Kwikxilver** [comment]
When I purchase an item from the shop, I get this error along with a massive lag spike - [pastebin link.](https://pastebin.com/Hm4wQgRc)

Probably related to this.

**Comment by jmanpenilla** [comment]
> When I purchase an item from the shop, I get this error along with a massive lag spike - [pastebin link.](https://pastebin.com/Hm4wQgRc)
> 
> Probably related to this.

Your issue looks more likely to come from whatever plugin this is from ```net.tnemc.core.common.api.Economy_TheNewEconomy.getBalance```

**Comment by Kwikxilver** [comment]
@jmanpenilla thanks, I will report to the mod author.

**Comment by DatblockCom** [comment]
Hello, I was able to test the plugin today. I have a spark sampler for ticks only over 500ms here, https://spark.lucko.me/#mfxsrcsEOu, "me.sat7.dynamicshop.events.JoinQuit.onPlayerJoin()80.00%".

**Comment by Lambsy** [comment]
Hello, I was able to test the plugin today. I have a spark sampler for ticks only over 500ms here, https://spark.lucko.me/#mfxsrcsEOu, "me.sat7.dynamicshop.events.JoinQuit.onPlayerJoin()80.00%".

**Comment by DatblockCom** [comment]
> Hello, I was able to test the plugin today. I have a spark sampler for ticks only over 500ms here, https://spark.lucko.me/#mfxsrcsEOu, "me.sat7.dynamicshop.events.JoinQuit.onPlayerJoin()80.00%".

DynamicShop version 2.11.8

**Comment by LucidAPs** [comment]
The performance is getting worse and worse the more I use the plugin.
![image](https://user-images.githubusercontent.com/42933023/110221214-9486e600-7ed3-11eb-8f2c-5df275bd0a69.png)
