### ISSUE TITLE
Signs not functional, just makes green text

### ISSUE THREAD

**Issue by Kwikxilver** [7sat/DynamicShop#38]
As I said in the title, I create the sign shop according to the config but it does not function on right click. All that happens is the shop title goes green and [ds] disappears.

Using latest version (2.11.8) with Paper. Let me know if you need any more info.

**Comment by 7sat** [comment]
It is not reproduced, but there is a lack of feedback on how to solve the problem when the sign is not installed properly.

**Comment by 7sat** [comment]
- 1st line : [ds] or [dshop] or [dynamicshop]
- 2nd line : shop name
- 3rd line : (Optional) item name
- 4th line : (Optional) 1st line will be replaced by this.

Alternative:
- 1st line : (empty)
- 2nd line : shop name
- 3rd line : (Optional)item name
- 4th line : (empty)
- Right click on sign.

- Sign must be placed on wall.
- Shop name is case sensitive.
- Item name is case insensitive.
