### ISSUE TITLE
Plugin API Feature Request

### ISSUE THREAD

**Issue by shmkane** [7sat/DynamicShop#43]
Hello, I'm the developer for the [SellStick](https://github.com/shmkane/SellStick) plugin on Spigot. 

Some users requested that I hook SellStick in with DynamicShop, such that when they use a SellStick item, the transaction will go through the DynamicShop.

I looked through the API, and noticed that there was a way to get the [SellPrice](https://github.com/7sat/SSDynamicShop/blob/0f46519fb361f968d3f008b396ec609df4cd3218/src/main/java/me/sat7/dynamicshop/DynaShopAPI.java#L185) for an item, but not a way to sell an item. 

In other words, I would like to be able to call a method with a similar signature to this:

```
    /**
     * Sells an item via DynamicShop and returns the sellPrice
     *
     * @param itemStack The itemStack to sell/
     * @returns the price the itemstack was sold for.
     */
    public static double sellItem(@NonNull ItemStack itemStack) {
                 // Checks to see if this item exists in any shops
                          // if exists,
                                   //sell item
                                   //return sell price
                         // else
                                  // throw some Exception, or return -1
    }
``` 

Even better would be if the method accepted an array of ItemStack objects so a chest, for example, could be sold in one cal to the API. But either would be fine.

If I have some time I may try to understand the plugin a bit better and submit a PR.

Thanks for the consideration.

**Comment by 7sat** [comment]
https://github.com/7sat/SSDynamicShop/commit/191252fdcfae01b3d334b52fcf8893fe8eb43275
I'm not sure this will work
