### ISSUE TITLE
Question / Feature asking

### ISSUE THREAD

**Issue by Grafhugo** [7sat/DynamicShop#49]
Hello i want to ask about the linking shops

How does they work?

IF i combine a with b
and i sell at A (a decreases)
will B increase?

If yes okey ignore this, if no could we add this? Its a perfect way to give "bad shops" like finishing shop better prices

**Comment by 7sat** [comment]
Using the linkto command, the two stores will share account balances.
It will not affect the price or stock of items in other stores.
