### ISSUE TITLE
Arrow up/arrow down color changing

### ISSUE THREAD

**Issue by ACluco1** [7sat/DynamicShop#50]
I would like to make improvements to recent changes to colors of arrows, we are able to change them, but this is not how we wanted to get it changed.

Explanation:

Lets say we got diamonds in our shop which median is 100 and stock is 100. Tax are 0%. This will be without arrows which is correct. But, when we will buy lets say 10 diamonds, the prices will change and arrows will appear. Arrows colors will appear kinda wrong, let me explain why.

Buy for 110 - (this will appear as RED arrow) - which is right, its red beacuse this item is more expensive than normal.
Sell for 110 - (this will appear as RED arrow) - this is not right, its red because its.. more profitable to sell? Dont think so :P The arrow should be GREEN for sure

Then, we will sell 20 diamonds to shop, so we will get prices like this -

Buy for 90 - (This will appear as GREEN arrow) - which is RIGHT! Its green, because you will save 10 money for this than normal.
Sell for 90 - (This will appear as GREEN arrow) - which is NOT right, its green because of what? .. you can sell less? doesnt make sence. This arrow should be definitely RED.

I hope you understand it :) (Sorry for my bad english tho) 

PS. This plugin should be premium, its really good, easy to use and set up, players are really enjoying price values rising and going down, so they will make more profitable shoping when .. you know, items get cheaper or more expensive :)

**Comment by 7sat** [comment]
https://github.com/7sat/DynamicShop/compare/767bd85588e6...3da0af97b0b3
Added one more pair of arrow strings.
