### ISSUE TITLE
DynamicShop Lang

### ISSUE THREAD

**Issue by BirminghamBoy** [7sat/DynamicShop#51]
Is it possible to improve the lang customisation for DynamicShop? For example, I am currently unable to remove lore from items such as the exit button. I am also unable to customise some buttons fully, such as the page change button (can only change the "Page" part of the name, making the page number colour inconsistent).

**Comment by 7sat** [comment]
https://github.com/7sat/DynamicShop/commit/bd31c9f1c2f9f8c0c564641985d25cbf1599877c

There is room for improvement, but I think this will solve the problem for now.
