### ISSUE TITLE
One permission for the entire Shop

### ISSUE THREAD

**Issue by Chris6ix** [7sat/DynamicShop#58]
It would be better if you could have one permission to generally be able to open the "Start Page" (/shop) instead of letting the players open the main shop menu and then having a permission per Shop...

**Comment by 7sat** [comment]
There are users who need individual permission settings for each store.
The permission of the /ds command is dshop.use and is turned on by default. You can turn that permission off.

**Comment by 7sat** [comment]
There is a problem that the message 'You do not have permission' is not displayed normally.
