### ISSUE TITLE
Add Ability to sort the "Item Palette"

### ISSUE THREAD

**Issue by Chris6ix** [7sat/DynamicShop#62]
It would be really nice if the "Item Palette" could be sorted to for example only display Blocks, Food or Armor

This would make the "Add All" Function a lot more useful

**Comment by 7sat** [comment]
You can achieve similar results by starting with a search (compass icon) in the Items palette and then using addAll.

**Comment by 7sat** [comment]
Regardless, it is true that there is room for improvement in the item palette.

**Comment by 7sat** [comment]
The premium version includes an improved palette.
You can search for similar items again by right-clicking in the search results.
Items can now be added continuously by left-clicking in the search results.
